// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiRm0HlV6sLcxelIMB_5UKULncJOCnDPw',
    appId: '1:513256279316:web:c02c57be15a163f07a8601',
    messagingSenderId: '513256279316',
    projectId: 'nova-expense-tracker-aa089',
    authDomain: 'nova-expense-tracker-aa089.firebaseapp.com',
    storageBucket: 'nova-expense-tracker-aa089.firebasestorage.app',
    measurementId: 'G-K20BC0N0S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8lX41BUVdt2-ljqmyqCYxxiQZhCTM7Tk',
    appId: '1:513256279316:android:ac3b8a02b97118f97a8601',
    messagingSenderId: '513256279316',
    projectId: 'nova-expense-tracker-aa089',
    storageBucket: 'nova-expense-tracker-aa089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr6YWNw8Z_Mf4ijpCQzaImsdOY0Un5dcs',
    appId: '1:513256279316:ios:5a6ed6aecc335cc97a8601',
    messagingSenderId: '513256279316',
    projectId: 'nova-expense-tracker-aa089',
    storageBucket: 'nova-expense-tracker-aa089.firebasestorage.app',
    iosClientId:
        '513256279316-5hsco92s8297ab59utljohlreonqjba3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nova',
  );
}
